name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'pull master'
        uses: actions/checkout@v2
      - name: 'setup ruby'
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: '2.6'
      - name: 'install jekyll'
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: 'build'
        run: | 
          bundle exec jekyll build -d _site
      - name: Deploy_To_GithubPage
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.JEKYLL_PAT }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.
          TARGET_FOLDER: site
          CLEAN: true # Automatically remove deleted files from the deploy branch
