name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: DEV
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'pull master'
        uses: actions/checkout@v3.3.0
      - name: 'setup ruby'
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '3.0'
      - name: 'install jekyll'
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: 'build'
        run: | 
          bundle exec jekyll build -d _site
      - name: Deploy_To_GithubPage
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          ACCESS_TOKEN: ${{ secrets.JEKYLL_PAT }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

